postgres:
  HOST: 89.23.112.6
  DBNAME: video_hosting
  USER: nikita
  PASS: 123nikita321
  PORT: 10500
s3:
  BUCKET_NAME: 61ca3438-78fc1d0a-8cd9-4c3b-b8b2-1ae1d32c9cb2
  ACCESS_KEY: 59H7BXKTSPO37BE1V7PQ
  SECRET_ACCESS_KEY: AY1JpYD70vCXQE1pnHu5IbFpYxCg6nZapXx3AHWQ
  REPLICATION_BUCKET_NAME: 61ca3438-874e5ed1-09d6-47ed-9a83-004e99280856
  REPLICATION_ACCESS_KEY: 59H7BXKTSPO37BE1V7PQ
  REPLICATION_SECRET_ACCESS_KEY: AY1JpYD70vCXQE1pnHu5IbFpYxCg6nZapXx3AHWQ
  REGION: ru-1
  URL: https://s3.timeweb.cloud
server:
  HOST: localhost
  PORT: 8080
